//! Example: Servo motor
//!
//!
//! ```text
//!                       ┌─────────────────────────────────────────────────────────────────┐
//!                       │SERVO Motor                                                      │
//!                       │   ┌────────────┐                Voltage                         │
//!                       │   │            │◄────────────────────────────────────────────┐  │
//!                       │   │   Servo    │                            ┌───────────────┐│  │
//!             degrees   │   │ Controller │    Voltage   ┌─────────┐ ┌►│ Potentiometer ├┘  │
//! Set point ●───────────┼──►│            ├─────────────►│         │ │ └───────────────┘   │
//!             (0:180)   │   │            │              │   DC    │ │   position          │
//!                       │   └────────────┘              │  Motor  ├─┴─────────────────────┼──────────►
//!       torque, inertia │                               │         │     (0:180)           │
//! Load ●────────────────┼──────────────────────────────►│         │                       │
//!                       │                               └─────────┘                       │
//!                       └─────────────────────────────────────────────────────────────────┘
//! ```

use std::iter;
use std::time::Duration;

use serde::{Deserialize, Serialize};

use nexosim::model::{BuildContext, Context, Model, ProtoModel, schedulable};
use nexosim::ports::{EventSinkReader, EventSource, Output, SinkState, event_queue};
use nexosim::simulation::{Mailbox, SimInit};
use nexosim::time::MonotonicTime;

use utilities::{pid::PidController, plot};

use std::f64::consts::PI;

/// Stepper motor.
#[derive(Serialize, Deserialize)]
pub struct DCMotor {
    /// Position [deg] -- output port.
    pub position: Output<f64>,

    /// Position [deg] -- internal state.
    pos: f64,
    /// Previous velocity [rad/s] -- internal state.
    prev_vel: f64,
    /// Previous acceleration [rad/s^2] -- internal state.
    prev_acc: f64,
    /// time of last position update -- internal state.
    last_position_update: Option<MonotonicTime>,
    /// Load on the motor -- internal state.
    load: Load,
    /// Torque generated by the motor wit maximal voltage -- constant.
    max_torque: f64,
    /// Maximal position of the servo [degrees] -- constant.
    max_position: f64,
    /// Voltage supplied to the servo [V] -- constant.
    supply_voltage: f64,
}

#[Model]
impl DCMotor {
    /// Create a new DC motor.
    pub fn new(
        max_torque: f64,
        max_position: f64,
        supply_voltage: f64,
        load: Load,
        position: f64,
    ) -> Self {
        assert!((0.0..=max_position).contains(&position));
        Self {
            position: Default::default(),
            pos: position,
            prev_vel: 0.0,
            prev_acc: 0.0,
            last_position_update: None,
            load,
            max_torque,
            max_position,
            supply_voltage,
        }
    }

    /// Broadcasts the initial position of the motor.
    #[nexosim(init)]
    async fn init(&mut self) {
        self.position.send(self.pos).await;
    }

    /// Motor voltage supplied from controller [V].
    ///
    /// Calculates motors position based on simplified model in which motor
    /// torque is propotional to voltage.
    pub async fn voltage_in(&mut self, voltage: f64, cx: &Context<Self>) {
        let now = cx.time();
        if let Some(prev_time) = self.last_position_update {
            let elapsed_time = now.duration_since(prev_time).as_secs_f64();
            // Current velocity calculated based on acceleration during last period.
            let vel = self.prev_vel + self.prev_acc * elapsed_time;
            // Integration of velocity over time to get position change, converted to degrees.
            self.pos += (self.prev_vel + vel) / 2.0 * elapsed_time / PI * 180.0;
            // Applies position limits.
            self.pos = self.pos.min(self.max_position);
            self.pos = self.pos.max(0.0);
            // Saves velocity for next iteration.
            self.prev_vel = vel;
        }
        // Saves time for next iteration.
        self.last_position_update = Some(now);
        // Calculates current acceleration to use at next iteration.
        let torque = voltage / self.supply_voltage * self.max_torque - self.load.torque;
        let acceleration = torque / self.load.inertia;
        self.prev_acc = acceleration;
        // Sends position.
        self.position.send(self.pos).await;
    }

    /// Load -- input port.
    pub fn load(&mut self, load: Load) {
        self.load = load;
    }
}

#[derive(Serialize, Deserialize, Clone)]
pub struct Load {
    /// Torque applied by the load [N·m].
    pub torque: f64,
    /// Rotetional inertia of the load [kg·m^2].
    pub inertia: f64,
}

/// Potentiometer measuring the motor's possition.
#[derive(Serialize, Deserialize)]
pub struct Potentiometer {
    /// Voltage corresponding to the position of servo [V] -- output port.
    pub voltage_out: Output<f64>,

    /// Voltage supplied to the servo [V] -- constant.
    supply_voltage: f64,
    /// Maximal position of the servo [degrees] -- constant.
    max_position: f64,
}

#[Model]
impl Potentiometer {
    /// Creates a new potentiometer.
    pub fn new(supply_voltage: f64, max_position: f64) -> Self {
        Self {
            voltage_out: Default::default(),
            supply_voltage,
            max_position,
        }
    }

    /// Measures the position of of motor and broadcasts output voltage.
    /// Adds noise with an amplitude of 0.5% of supply voltage.
    pub async fn measure_position(&mut self, position: f64) {
        self.voltage_out
            .send(
                (position / self.max_position + rand::random_range(-0.005..=0.005))
                    * self.supply_voltage,
            )
            .await;
    }
}

/// Servo motor controller utilizing PID algorithm.
#[derive(Serialize, Deserialize)]
pub struct ServoController {
    /// Voltage controlling the motor [V] -- output port.
    pub voltage_out: Output<f64>,

    /// Position of the motor read from potentiometer [deg] -- internal state.
    pos: f64,
    /// Set point for regulator [deg] -- internal state.
    sp: Option<f64>,
    /// Voltage supplied to the servo [V] -- constant.
    supply_voltage: f64,
    /// Maximal position of the servo [degrees] -- constant.
    max_position: f64,
    /// Period of the control loop [s] -- constant.
    period: f64,
    /// Time of previos iteration [-] -- internal state.
    last_control_update: Option<MonotonicTime>,
    /// Implementation of PID controller
    pid_impl: PidController,
}

#[Model]
impl ServoController {
    /// Creates a new servo controller.
    pub fn new(supply_voltage: f64, period: f64, max_position: f64, pid_config: PidConfig) -> Self {
        assert!(period > 0.0);
        let mut pid_impl = PidController::new_with_limits(
            pid_config.proportional_gain,
            pid_config.integral_gain,
            pid_config.derivative_gain,
            Some(-1.0),
            Some(1.0),
        );
        pid_impl.set_master_gain(pid_config.master_gain);

        Self {
            voltage_out: Default::default(),
            pos: 0.0,
            sp: None,
            supply_voltage,
            max_position,
            period,
            last_control_update: None,
            pid_impl,
        }
    }

    /// Reads voltage from the potentiometer.
    pub async fn read_position(&mut self, voltage: f64) {
        self.pos = (voltage / self.supply_voltage) * self.max_position;
    }

    /// Sets the set point and shedules first iteration if necessary.
    pub async fn set_point(&mut self, value: f64, cx: &Context<Self>) {
        let is_idle = self.sp.is_none();
        self.sp = Some(value);
        if is_idle {
            self.set_output((), cx).await;
        }
    }

    /// Sends voltage and schedules next iteration.
    #[nexosim(schedulable)]
    async fn set_output(&mut self, _: (), cx: &Context<Self>) {
        let error = self.sp.unwrap() - self.pos;
        // Calculates time from previos iteration.
        // Uses period instead during first iteration.
        let now = cx.time();
        let dt;
        if let Some(time) = self.last_control_update {
            dt = now.duration_since(time).as_secs_f64();
        } else {
            dt = self.period;
        }
        self.last_control_update = Some(now);
        // Calculating control value using PID regulator and denormalizing it.
        let voltage = self.pid_impl.update(error, dt) * self.supply_voltage;
        self.voltage_out.send(voltage).await;

        let duration = Duration::from_secs_f64(self.period);

        // Schedules the next iteration.
        cx.schedule_event(duration, schedulable!(Self::set_output), ())
            .unwrap();
    }
}

pub struct PidConfig {
    proportional_gain: f64,
    integral_gain: f64,
    derivative_gain: f64,
    master_gain: f64,
}

impl PidConfig {
    pub fn new(
        proportional_gain: f64,
        integral_gain: f64,
        derivative_gain: f64,
        master_gain: f64,
    ) -> Self {
        Self {
            proportional_gain,
            integral_gain,
            derivative_gain,
            master_gain,
        }
    }
}

/// The parent model which submodels are DCMotor, Potentiometer
/// and ServoController.
#[derive(Serialize, Deserialize)]
pub struct ServoAssembly {
    /// Private output for submodel connection.
    setpoint: Output<f64>,
    /// Private output for submodel connection.
    load: Output<Load>,
}

#[Model]
impl ServoAssembly {
    /// The parent model has a module-private constructor.
    fn new() -> Self {
        Self {
            setpoint: Default::default(),
            load: Default::default(),
        }
    }

    /// Set point of the motor position [degrees] -- input port.
    pub async fn setpoint(&mut self, setpoint: f64) {
        self.setpoint.send(setpoint).await;
    }

    /// Load on the motor -- input port.
    pub async fn load(&mut self, load: Load) {
        self.load.send(load).await;
    }
}

/// Prototype for 'ServoAssembly'.
pub struct ProtoServoAssembly {
    pub position: Output<f64>,
    init_pos: f64,
    max_torque: f64,
    max_position: f64,
    supply_voltage: f64,
    period: f64,
    pid_config: PidConfig,
    load: Load,
}

impl ProtoServoAssembly {
    /// The prototype has a public constructor.
    pub fn new(
        init_pos: f64,
        max_torque: f64,
        max_position: f64,
        supply_voltage: f64,
        period: f64,
        pid_config: PidConfig,
        load: Load,
    ) -> Self {
        Self {
            position: Default::default(),
            init_pos,
            max_torque,
            max_position,
            supply_voltage,
            period,
            pid_config,
            load,
        }
    }
    // Input methods are in the model itself.
}

impl ProtoModel for ProtoServoAssembly {
    type Model = ServoAssembly;

    fn build(self, cx: &mut BuildContext<Self>) -> (ServoAssembly, ()) {
        // Creates parent model.
        let mut assembly = ServoAssembly::new();
        // Creates child models.
        let mut motor = DCMotor::new(
            self.max_torque,
            self.max_position,
            self.supply_voltage,
            self.load,
            self.init_pos,
        );
        let mut potentiometer = Potentiometer::new(self.supply_voltage, self.max_position);
        let mut controller = ServoController::new(
            self.supply_voltage,
            self.period,
            self.max_position,
            self.pid_config,
        );

        // Mailboxes.
        let motor_mbox = Mailbox::new();
        let potentiometer_mbox = Mailbox::new();
        let controller_mbox = Mailbox::new();

        // Connections
        assembly
            .setpoint
            .connect(ServoController::set_point, &controller_mbox);
        assembly.load.connect(DCMotor::load, &motor_mbox);
        controller
            .voltage_out
            .connect(DCMotor::voltage_in, &motor_mbox);
        potentiometer
            .voltage_out
            .connect(ServoController::read_position, &controller_mbox);
        // Move the prototype's output to the submodel. The `self.position`
        // output can be cloned if necessary if several submodels need access to
        // it.
        motor.position = self.position;
        // Internal connection made after move.
        motor
            .position
            .connect(Potentiometer::measure_position, &potentiometer_mbox);

        cx.add_submodel(motor, motor_mbox, "motor");
        cx.add_submodel(potentiometer, potentiometer_mbox, "potentiometer");
        cx.add_submodel(controller, controller_mbox, "controller");

        (assembly, ())
    }
}

fn main() -> Result<(), nexosim::simulation::SimulationError> {
    // Parameters.
    let init_pos: f64 = 0.0;
    let period = 0.01;
    let max_torque = 0.2;
    let max_position = 180.0;
    let supply_voltage = 6.0;
    let load = Load {
        torque: 0.0,
        // Inertia od 100g disc with 10cm radius.
        inertia: 0.0005,
    };
    let pid_config = PidConfig {
        proportional_gain: 20.0,
        integral_gain: 10.0,
        derivative_gain: 2.0,
        master_gain: 0.001,
    };

    // Model
    let mut servo = ProtoServoAssembly::new(
        init_pos,
        max_torque,
        max_position,
        supply_voltage,
        period,
        pid_config,
        load,
    );

    let servo_mbox = Mailbox::new();
    let servo_addr = servo_mbox.address();

    // Endpoints
    let mut bench = SimInit::new();

    let set_point = EventSource::new()
        .connect(ServoAssembly::setpoint, &servo_addr)
        .register(&mut bench);
    let motor_load = EventSource::new()
        .connect(ServoAssembly::load, &servo_addr)
        .register(&mut bench);

    let (sink, mut position) = event_queue(SinkState::Enabled);
    servo.position.connect_sink(sink);

    // Bench assembly and initialization.
    let t0 = MonotonicTime::EPOCH; // arbitrary since models do not depend on absolute time
    let mut simu = bench.add_model(servo, servo_mbox, "servo").init(t0)?;

    // ----------
    // Simulation.
    // ----------

    let scheduler = simu.scheduler();

    // Check initial conditions.
    let mut t = t0;
    assert_eq!(simu.time(), t);
    assert_eq!(position.try_read(), Some(0.0));
    assert!(position.try_read().is_none());

    // Start the servo in 1s with a set point of 90 degrees.
    scheduler
        .schedule_event(Duration::from_secs(1), &set_point, 90.0)
        .unwrap();

    // Advance simulation to one second after servo starts.
    simu.step_until(Duration::new(2, 0))?;

    // Check if servo is around setpoint 1 second after start.
    t += Duration::new(2, 0);
    assert_eq!(simu.time(), t);
    let current_pos = iter::from_fn(|| position.try_read()).last().unwrap();
    assert!((85.0..=95.0).contains(&current_pos));

    // Change the set point to 150 degrees.
    simu.process_event(&set_point, 150.0)?;

    // Advance the simulation time to the moment immediately after the change
    // and check whether the servo has not yet reached the setpoint.
    simu.step_until(Duration::new(0, 50_000_000))?;
    t += Duration::new(0, 50_000_000);
    assert_eq!(simu.time(), t);
    let mut current_pos = iter::from_fn(|| position.try_read()).last().unwrap();
    assert!(current_pos < 140.0);

    // Advance simulation time and check if servo is around setpoint 1 second after set point change.
    simu.step_until(Duration::new(0, 950_000_000))?;
    t += Duration::new(0, 950_000_000);
    assert_eq!(simu.time(), t);
    current_pos = iter::from_fn(|| position.try_read()).last().unwrap();
    assert!((145.0..=155.0).contains(&current_pos));

    // Apply torque on the motor
    let load = Load {
        torque: 0.05,
        inertia: 0.0005,
    };
    simu.process_event(&motor_load, load)?;

    // Advance the simulation time and check wheather the position changed due to the load applied.
    simu.step_until(Duration::new(0, 200_000_000))?;
    t += Duration::new(0, 200_000_000);
    assert_eq!(simu.time(), t);
    current_pos = iter::from_fn(|| position.try_read()).last().unwrap();
    assert!(current_pos < 145.0);

    // Advance the simulation time and check wheather the position stabilized arround
    // set point 3 seconds after the load were applied.
    simu.step_until(Duration::new(2, 800_000_000))?;
    t += Duration::new(2, 800_000_000);
    assert_eq!(simu.time(), t);
    current_pos = iter::from_fn(|| position.try_read()).last().unwrap();
    assert!((145.0..=155.0).contains(&current_pos));

    // Plot creation
    // Plot shows several setpoint changes and their impact on the servo position.

    // Zero torque.
    let load = Load {
        torque: 0.00,
        inertia: 0.0005,
    };
    simu.process_event(&motor_load, load)?;

    // Advance simulation time to stabilize the servo without collecting position values.
    position.disable();
    simu.step_until(Duration::new(10, 0))?;
    position.enable();

    // Set points for the tajectory, vector: [[time, value]].
    // First value is current set point.
    let trajectory: Vec<(u64, f64)> = vec![(0, 150.0), (2, 60.0), (6, 0.0), (8, 90.0)];

    // Scheduling set point changes
    for (time, value) in &trajectory[1..] {
        scheduler
            .schedule_event(Duration::from_secs(*time), &set_point, *value)
            .unwrap();
    }

    // Length of the simulation for the plot [s].
    let sim_len = 14;

    // Simulating
    simu.step_until(Duration::new(sim_len, 0))?;

    // Formatting the set point vector for the plot drawing function.
    let mut trajectory_for_drawing: Vec<[f64; 2]> = Vec::new();
    for i in 0..trajectory.len() - 1 {
        trajectory_for_drawing.push([
            trajectory.get(i).unwrap().0 as f64,
            trajectory.get(i).unwrap().1,
        ]);
        trajectory_for_drawing.push([
            trajectory.get(i + 1).unwrap().0 as f64,
            trajectory.get(i).unwrap().1,
        ]);
    }
    trajectory_for_drawing.push([
        trajectory.last().unwrap().0 as f64,
        trajectory.last().unwrap().1,
    ]);
    trajectory_for_drawing.push([sim_len as f64, trajectory.last().unwrap().1]);

    // Collecting all positions to a vector.
    let positions: Vec<f64> = iter::from_fn(|| position.try_read()).collect();

    // Formatting the positions vector for the plot drawing function.
    let positions_with_time: Vec<[f64; 2]> = positions
        .iter()
        .enumerate()
        .map(|(id, pos)| [id as f64 * period, *pos])
        .collect();

    plot::plot_series(&[
        ("position", &positions_with_time),
        ("set point", &trajectory_for_drawing),
    ]);
    Ok(())
}
