// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Error {
    #[prost(enumeration = "ErrorCode", tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Path {
    #[prost(string, repeated, tag = "1")]
    pub segments: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EventSourceSchema {
    #[prost(message, optional, tag = "1")]
    pub source: ::core::option::Option<Path>,
    #[prost(string, tag = "2")]
    pub event: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QuerySourceSchema {
    #[prost(message, optional, tag = "1")]
    pub source: ::core::option::Option<Path>,
    #[prost(string, tag = "2")]
    pub request: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub reply: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EventSinkSchema {
    #[prost(message, optional, tag = "1")]
    pub sink: ::core::option::Option<Path>,
    #[prost(string, tag = "2")]
    pub event: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EventKey {
    #[prost(uint64, tag = "1")]
    pub subkey1: u64,
    #[prost(uint64, tag = "2")]
    pub subkey2: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BuildRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub cfg: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BuildReply {
    /// Always returns exactly 1 variant.
    #[prost(oneof = "build_reply::Result", tags = "1, 100")]
    pub result: ::core::option::Option<build_reply::Result>,
}
/// Nested message and enum types in `BuildReply`.
pub mod build_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Empty(()),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InitRequest {
    #[prost(message, optional, tag = "1")]
    pub time: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InitReply {
    /// Always returns exactly 1 variant.
    #[prost(oneof = "init_reply::Result", tags = "1, 100")]
    pub result: ::core::option::Option<init_reply::Result>,
}
/// Nested message and enum types in `InitReply`.
pub mod init_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Empty(()),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InitAndRunRequest {
    #[prost(message, optional, tag = "1")]
    pub time: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InitAndRunReply {
    /// Always returns exactly 1 variant.
    #[prost(oneof = "init_and_run_reply::Result", tags = "1, 100")]
    pub result: ::core::option::Option<init_and_run_reply::Result>,
}
/// Nested message and enum types in `InitAndRunReply`.
pub mod init_and_run_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Time(::prost_types::Timestamp),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RestoreRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub state: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RestoreReply {
    /// Always returns exactly 1 variant.
    #[prost(oneof = "restore_reply::Result", tags = "1, 100")]
    pub result: ::core::option::Option<restore_reply::Result>,
}
/// Nested message and enum types in `RestoreReply`.
pub mod restore_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Empty(()),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RestoreAndRunRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub state: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RestoreAndRunReply {
    /// Always returns exactly 1 variant.
    #[prost(oneof = "restore_and_run_reply::Result", tags = "1, 100")]
    pub result: ::core::option::Option<restore_and_run_reply::Result>,
}
/// Nested message and enum types in `RestoreAndRunReply`.
pub mod restore_and_run_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Time(::prost_types::Timestamp),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TerminateRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TerminateReply {
    /// Always returns exactly 1 variant.
    #[prost(oneof = "terminate_reply::Result", tags = "1, 100")]
    pub result: ::core::option::Option<terminate_reply::Result>,
}
/// Nested message and enum types in `TerminateReply`.
pub mod terminate_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Empty(()),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HaltRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HaltReply {
    /// Always returns exactly 1 variant.
    #[prost(oneof = "halt_reply::Result", tags = "1, 100")]
    pub result: ::core::option::Option<halt_reply::Result>,
}
/// Nested message and enum types in `HaltReply`.
pub mod halt_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Empty(()),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SaveRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SaveReply {
    /// Always returns exactly 1 variant.
    #[prost(oneof = "save_reply::Result", tags = "1, 100")]
    pub result: ::core::option::Option<save_reply::Result>,
}
/// Nested message and enum types in `SaveReply`.
pub mod save_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(bytes, tag = "1")]
        State(::prost::alloc::vec::Vec<u8>),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TimeRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TimeReply {
    /// Always returns exactly 1 variant.
    #[prost(oneof = "time_reply::Result", tags = "1, 100")]
    pub result: ::core::option::Option<time_reply::Result>,
}
/// Nested message and enum types in `TimeReply`.
pub mod time_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Time(::prost_types::Timestamp),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StepRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StepReply {
    /// Always returns exactly 1 variant.
    #[prost(oneof = "step_reply::Result", tags = "1, 100")]
    pub result: ::core::option::Option<step_reply::Result>,
}
/// Nested message and enum types in `StepReply`.
pub mod step_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Time(::prost_types::Timestamp),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StepUntilRequest {
    /// Always returns exactly 1 variant.
    #[prost(oneof = "step_until_request::Deadline", tags = "1, 2")]
    pub deadline: ::core::option::Option<step_until_request::Deadline>,
}
/// Nested message and enum types in `StepUntilRequest`.
pub mod step_until_request {
    /// Always returns exactly 1 variant.
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Deadline {
        #[prost(message, tag = "1")]
        Time(::prost_types::Timestamp),
        #[prost(message, tag = "2")]
        Duration(::prost_types::Duration),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StepUntilReply {
    /// Always returns exactly 1 variant.
    #[prost(oneof = "step_until_reply::Result", tags = "1, 100")]
    pub result: ::core::option::Option<step_until_reply::Result>,
}
/// Nested message and enum types in `StepUntilReply`.
pub mod step_until_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Time(::prost_types::Timestamp),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RunRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RunReply {
    /// Always returns exactly 1 variant.
    #[prost(oneof = "run_reply::Result", tags = "1, 100")]
    pub result: ::core::option::Option<run_reply::Result>,
}
/// Nested message and enum types in `RunReply`.
pub mod run_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Time(::prost_types::Timestamp),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListEventSourcesRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListEventSourcesReply {
    /// This field is hoisted because protobuf3 does not support `repeated` within
    /// a `oneof`. It is Always empty if an error is returned.
    #[prost(message, repeated, tag = "1")]
    pub sources: ::prost::alloc::vec::Vec<Path>,
    /// Always returns exactly 1 variant.
    #[prost(oneof = "list_event_sources_reply::Result", tags = "10, 100")]
    pub result: ::core::option::Option<list_event_sources_reply::Result>,
}
/// Nested message and enum types in `ListEventSourcesReply`.
pub mod list_event_sources_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "10")]
        Empty(()),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetEventSourceSchemasRequest {
    #[prost(message, repeated, tag = "1")]
    pub sources: ::prost::alloc::vec::Vec<Path>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetEventSourceSchemasReply {
    /// This field is hoisted because protobuf3 does not support `repeated` within
    /// a `oneof`. It is Always empty if an error is returned.
    #[prost(message, repeated, tag = "1")]
    pub schemas: ::prost::alloc::vec::Vec<EventSourceSchema>,
    /// Always returns exactly 1 variant.
    #[prost(oneof = "get_event_source_schemas_reply::Result", tags = "10, 100")]
    pub result: ::core::option::Option<get_event_source_schemas_reply::Result>,
}
/// Nested message and enum types in `GetEventSourceSchemasReply`.
pub mod get_event_source_schemas_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "10")]
        Empty(()),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListQuerySourcesRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListQuerySourcesReply {
    /// This field is hoisted because protobuf3 does not support `repeated` within
    /// a `oneof`. It is Always empty if an error is returned
    #[prost(message, repeated, tag = "1")]
    pub sources: ::prost::alloc::vec::Vec<Path>,
    /// Always returns exactly 1 variant.
    #[prost(oneof = "list_query_sources_reply::Result", tags = "10, 100")]
    pub result: ::core::option::Option<list_query_sources_reply::Result>,
}
/// Nested message and enum types in `ListQuerySourcesReply`.
pub mod list_query_sources_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "10")]
        Empty(()),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetQuerySourceSchemasRequest {
    #[prost(message, repeated, tag = "1")]
    pub sources: ::prost::alloc::vec::Vec<Path>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetQuerySourceSchemasReply {
    /// This field is hoisted because protobuf3 does not support `repeated` within
    /// a `oneof`. It is Always empty if an error is returned.
    #[prost(message, repeated, tag = "1")]
    pub schemas: ::prost::alloc::vec::Vec<QuerySourceSchema>,
    /// Always returns exactly 1 variant.
    #[prost(oneof = "get_query_source_schemas_reply::Result", tags = "10, 100")]
    pub result: ::core::option::Option<get_query_source_schemas_reply::Result>,
}
/// Nested message and enum types in `GetQuerySourceSchemasReply`.
pub mod get_query_source_schemas_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "10")]
        Empty(()),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListEventSinksRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListEventSinksReply {
    /// This field is hoisted because protobuf3 does not support `repeated` within
    /// a `oneof`. It is Always empty if an error is returned.
    #[prost(message, repeated, tag = "1")]
    pub sinks: ::prost::alloc::vec::Vec<Path>,
    /// Always returns exactly 1 variant.
    #[prost(oneof = "list_event_sinks_reply::Result", tags = "10, 100")]
    pub result: ::core::option::Option<list_event_sinks_reply::Result>,
}
/// Nested message and enum types in `ListEventSinksReply`.
pub mod list_event_sinks_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "10")]
        Empty(()),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetEventSinkSchemasRequest {
    #[prost(message, repeated, tag = "1")]
    pub sinks: ::prost::alloc::vec::Vec<Path>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetEventSinkSchemasReply {
    /// This field is hoisted because protobuf3 does not support `repeated` within
    /// a `oneof`. It is Always empty if an error is returned.
    #[prost(message, repeated, tag = "1")]
    pub schemas: ::prost::alloc::vec::Vec<EventSinkSchema>,
    /// Always returns exactly 1 variant.
    #[prost(oneof = "get_event_sink_schemas_reply::Result", tags = "10, 100")]
    pub result: ::core::option::Option<get_event_sink_schemas_reply::Result>,
}
/// Nested message and enum types in `GetEventSinkSchemasReply`.
pub mod get_event_sink_schemas_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "10")]
        Empty(()),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InjectEventRequest {
    #[prost(message, optional, tag = "3")]
    pub source: ::core::option::Option<Path>,
    #[prost(bytes = "vec", tag = "4")]
    pub event: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InjectEventReply {
    /// Always returns exactly 1 variant.
    #[prost(oneof = "inject_event_reply::Result", tags = "1, 100")]
    pub result: ::core::option::Option<inject_event_reply::Result>,
}
/// Nested message and enum types in `InjectEventReply`.
pub mod inject_event_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Empty(()),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ScheduleEventRequest {
    #[prost(message, optional, tag = "3")]
    pub source: ::core::option::Option<Path>,
    #[prost(bytes = "vec", tag = "4")]
    pub event: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "5")]
    pub period: ::core::option::Option<::prost_types::Duration>,
    #[prost(bool, tag = "6")]
    pub with_key: bool,
    /// Expects exactly 1 variant.
    #[prost(oneof = "schedule_event_request::Deadline", tags = "1, 2")]
    pub deadline: ::core::option::Option<schedule_event_request::Deadline>,
}
/// Nested message and enum types in `ScheduleEventRequest`.
pub mod schedule_event_request {
    /// Expects exactly 1 variant.
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Deadline {
        #[prost(message, tag = "1")]
        Time(::prost_types::Timestamp),
        #[prost(message, tag = "2")]
        Duration(::prost_types::Duration),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ScheduleEventReply {
    /// Always returns exactly 1 variant.
    #[prost(oneof = "schedule_event_reply::Result", tags = "1, 2, 100")]
    pub result: ::core::option::Option<schedule_event_reply::Result>,
}
/// Nested message and enum types in `ScheduleEventReply`.
pub mod schedule_event_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Empty(()),
        #[prost(message, tag = "2")]
        Key(super::EventKey),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelEventRequest {
    #[prost(message, optional, tag = "1")]
    pub key: ::core::option::Option<EventKey>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelEventReply {
    /// Always returns exactly 1 variant.
    #[prost(oneof = "cancel_event_reply::Result", tags = "1, 100")]
    pub result: ::core::option::Option<cancel_event_reply::Result>,
}
/// Nested message and enum types in `CancelEventReply`.
pub mod cancel_event_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Empty(()),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProcessEventRequest {
    #[prost(message, optional, tag = "1")]
    pub source: ::core::option::Option<Path>,
    #[prost(bytes = "vec", tag = "2")]
    pub event: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProcessEventReply {
    /// Always returns exactly 1 variant.
    #[prost(oneof = "process_event_reply::Result", tags = "1, 100")]
    pub result: ::core::option::Option<process_event_reply::Result>,
}
/// Nested message and enum types in `ProcessEventReply`.
pub mod process_event_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Empty(()),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ScheduleQueryRequest {
    #[prost(message, optional, tag = "3")]
    pub source: ::core::option::Option<Path>,
    #[prost(bytes = "vec", tag = "4")]
    pub request: ::prost::alloc::vec::Vec<u8>,
    /// Expects exactly 1 variant.
    #[prost(oneof = "schedule_query_request::Deadline", tags = "1, 2")]
    pub deadline: ::core::option::Option<schedule_query_request::Deadline>,
}
/// Nested message and enum types in `ScheduleQueryRequest`.
pub mod schedule_query_request {
    /// Expects exactly 1 variant.
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Deadline {
        #[prost(message, tag = "1")]
        Time(::prost_types::Timestamp),
        #[prost(message, tag = "2")]
        Duration(::prost_types::Duration),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ScheduleQueryReply {
    /// This field is hoisted because protobuf3 does not support `repeated` within
    /// a `oneof`. It is Always empty if an error is returned
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub replies: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Always returns exactly 1 variant.
    #[prost(oneof = "schedule_query_reply::Result", tags = "10, 100")]
    pub result: ::core::option::Option<schedule_query_reply::Result>,
}
/// Nested message and enum types in `ScheduleQueryReply`.
pub mod schedule_query_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "10")]
        Empty(()),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProcessQueryRequest {
    #[prost(message, optional, tag = "1")]
    pub source: ::core::option::Option<Path>,
    #[prost(bytes = "vec", tag = "2")]
    pub request: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProcessQueryReply {
    /// This field is hoisted because protobuf3 does not support `repeated` within
    /// a `oneof`. It is Always empty if an error is returned
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub replies: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Always returns exactly 1 variant.
    #[prost(oneof = "process_query_reply::Result", tags = "10, 100")]
    pub result: ::core::option::Option<process_query_reply::Result>,
}
/// Nested message and enum types in `ProcessQueryReply`.
pub mod process_query_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "10")]
        Empty(()),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TryReadEventsRequest {
    #[prost(message, optional, tag = "1")]
    pub sink: ::core::option::Option<Path>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TryReadEventsReply {
    /// This field is hoisted because protobuf3 does not support `repeated` within
    /// a `oneof`. It is Always empty if an error is returned
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub events: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Always returns exactly 1 variant.
    #[prost(oneof = "try_read_events_reply::Result", tags = "10, 100")]
    pub result: ::core::option::Option<try_read_events_reply::Result>,
}
/// Nested message and enum types in `TryReadEventsReply`.
pub mod try_read_events_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "10")]
        Empty(()),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadEventRequest {
    #[prost(message, optional, tag = "1")]
    pub sink: ::core::option::Option<Path>,
    #[prost(message, optional, tag = "2")]
    pub timeout: ::core::option::Option<::prost_types::Duration>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadEventReply {
    /// Always returns exactly 1 variant.
    #[prost(oneof = "read_event_reply::Result", tags = "1, 100")]
    pub result: ::core::option::Option<read_event_reply::Result>,
}
/// Nested message and enum types in `ReadEventReply`.
pub mod read_event_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(bytes, tag = "1")]
        Event(::prost::alloc::vec::Vec<u8>),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnableSinkRequest {
    #[prost(message, optional, tag = "1")]
    pub sink: ::core::option::Option<Path>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnableSinkReply {
    /// Always returns exactly 1 variant.
    #[prost(oneof = "enable_sink_reply::Result", tags = "10, 100")]
    pub result: ::core::option::Option<enable_sink_reply::Result>,
}
/// Nested message and enum types in `EnableSinkReply`.
pub mod enable_sink_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "10")]
        Empty(()),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DisableSinkRequest {
    #[prost(message, optional, tag = "1")]
    pub sink: ::core::option::Option<Path>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DisableSinkReply {
    /// Always returns exactly 1 variant.
    #[prost(oneof = "disable_sink_reply::Result", tags = "10, 100")]
    pub result: ::core::option::Option<disable_sink_reply::Result>,
}
/// Nested message and enum types in `DisableSinkReply`.
pub mod disable_sink_reply {
    /// Always returns exactly 1 variant.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "10")]
        Empty(()),
        #[prost(message, tag = "100")]
        Error(super::Error),
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ErrorCode {
    /// Generic errors.
    InternalError = 0,
    MissingArgument = 1,
    InvalidTime = 2,
    InvalidPeriod = 3,
    InvalidDeadline = 4,
    InvalidMessage = 5,
    InvalidKey = 6,
    InvalidTimeout = 7,
    /// Bench building and initialization errors.
    BenchPanic = 20,
    BenchError = 21,
    BenchNotBuilt = 22,
    DuplicateEventSource = 23,
    DuplicateQuerySource = 24,
    DuplicateEventSink = 25,
    InvalidBenchConfig = 26,
    BenchAlreadyBuilt = 27,
    /// Simulation runtime error.
    SimulationPanic = 40,
    SimulationNotStarted = 42,
    SimulationTerminated = 43,
    SimulationDeadlock = 44,
    SimulationMessageLoss = 45,
    SimulationNoRecipient = 46,
    SimulationTimeout = 47,
    SimulationOutOfSync = 48,
    SimulationBadQuery = 49,
    SimulationTimeOutOfRange = 50,
    /// Monitoring errors.
    EventSourceNotFound = 60,
    QuerySourceNotFound = 61,
    SinkNotFound = 62,
    SinkTerminated = 63,
    SinkReadRace = 64,
    SinkReadTimeout = 65,
    InvalidEventType = 66,
    InvalidQueryType = 67,
    /// Serialization error.
    SaveError = 80,
    RestoreError = 81,
}
impl ErrorCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::InternalError => "INTERNAL_ERROR",
            Self::MissingArgument => "MISSING_ARGUMENT",
            Self::InvalidTime => "INVALID_TIME",
            Self::InvalidPeriod => "INVALID_PERIOD",
            Self::InvalidDeadline => "INVALID_DEADLINE",
            Self::InvalidMessage => "INVALID_MESSAGE",
            Self::InvalidKey => "INVALID_KEY",
            Self::InvalidTimeout => "INVALID_TIMEOUT",
            Self::BenchPanic => "BENCH_PANIC",
            Self::BenchError => "BENCH_ERROR",
            Self::BenchNotBuilt => "BENCH_NOT_BUILT",
            Self::DuplicateEventSource => "DUPLICATE_EVENT_SOURCE",
            Self::DuplicateQuerySource => "DUPLICATE_QUERY_SOURCE",
            Self::DuplicateEventSink => "DUPLICATE_EVENT_SINK",
            Self::InvalidBenchConfig => "INVALID_BENCH_CONFIG",
            Self::BenchAlreadyBuilt => "BENCH_ALREADY_BUILT",
            Self::SimulationPanic => "SIMULATION_PANIC",
            Self::SimulationNotStarted => "SIMULATION_NOT_STARTED",
            Self::SimulationTerminated => "SIMULATION_TERMINATED",
            Self::SimulationDeadlock => "SIMULATION_DEADLOCK",
            Self::SimulationMessageLoss => "SIMULATION_MESSAGE_LOSS",
            Self::SimulationNoRecipient => "SIMULATION_NO_RECIPIENT",
            Self::SimulationTimeout => "SIMULATION_TIMEOUT",
            Self::SimulationOutOfSync => "SIMULATION_OUT_OF_SYNC",
            Self::SimulationBadQuery => "SIMULATION_BAD_QUERY",
            Self::SimulationTimeOutOfRange => "SIMULATION_TIME_OUT_OF_RANGE",
            Self::EventSourceNotFound => "EVENT_SOURCE_NOT_FOUND",
            Self::QuerySourceNotFound => "QUERY_SOURCE_NOT_FOUND",
            Self::SinkNotFound => "SINK_NOT_FOUND",
            Self::SinkTerminated => "SINK_TERMINATED",
            Self::SinkReadRace => "SINK_READ_RACE",
            Self::SinkReadTimeout => "SINK_READ_TIMEOUT",
            Self::InvalidEventType => "INVALID_EVENT_TYPE",
            Self::InvalidQueryType => "INVALID_QUERY_TYPE",
            Self::SaveError => "SAVE_ERROR",
            Self::RestoreError => "RESTORE_ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "INTERNAL_ERROR" => Some(Self::InternalError),
            "MISSING_ARGUMENT" => Some(Self::MissingArgument),
            "INVALID_TIME" => Some(Self::InvalidTime),
            "INVALID_PERIOD" => Some(Self::InvalidPeriod),
            "INVALID_DEADLINE" => Some(Self::InvalidDeadline),
            "INVALID_MESSAGE" => Some(Self::InvalidMessage),
            "INVALID_KEY" => Some(Self::InvalidKey),
            "INVALID_TIMEOUT" => Some(Self::InvalidTimeout),
            "BENCH_PANIC" => Some(Self::BenchPanic),
            "BENCH_ERROR" => Some(Self::BenchError),
            "BENCH_NOT_BUILT" => Some(Self::BenchNotBuilt),
            "DUPLICATE_EVENT_SOURCE" => Some(Self::DuplicateEventSource),
            "DUPLICATE_QUERY_SOURCE" => Some(Self::DuplicateQuerySource),
            "DUPLICATE_EVENT_SINK" => Some(Self::DuplicateEventSink),
            "INVALID_BENCH_CONFIG" => Some(Self::InvalidBenchConfig),
            "BENCH_ALREADY_BUILT" => Some(Self::BenchAlreadyBuilt),
            "SIMULATION_PANIC" => Some(Self::SimulationPanic),
            "SIMULATION_NOT_STARTED" => Some(Self::SimulationNotStarted),
            "SIMULATION_TERMINATED" => Some(Self::SimulationTerminated),
            "SIMULATION_DEADLOCK" => Some(Self::SimulationDeadlock),
            "SIMULATION_MESSAGE_LOSS" => Some(Self::SimulationMessageLoss),
            "SIMULATION_NO_RECIPIENT" => Some(Self::SimulationNoRecipient),
            "SIMULATION_TIMEOUT" => Some(Self::SimulationTimeout),
            "SIMULATION_OUT_OF_SYNC" => Some(Self::SimulationOutOfSync),
            "SIMULATION_BAD_QUERY" => Some(Self::SimulationBadQuery),
            "SIMULATION_TIME_OUT_OF_RANGE" => Some(Self::SimulationTimeOutOfRange),
            "EVENT_SOURCE_NOT_FOUND" => Some(Self::EventSourceNotFound),
            "QUERY_SOURCE_NOT_FOUND" => Some(Self::QuerySourceNotFound),
            "SINK_NOT_FOUND" => Some(Self::SinkNotFound),
            "SINK_TERMINATED" => Some(Self::SinkTerminated),
            "SINK_READ_RACE" => Some(Self::SinkReadRace),
            "SINK_READ_TIMEOUT" => Some(Self::SinkReadTimeout),
            "INVALID_EVENT_TYPE" => Some(Self::InvalidEventType),
            "INVALID_QUERY_TYPE" => Some(Self::InvalidQueryType),
            "SAVE_ERROR" => Some(Self::SaveError),
            "RESTORE_ERROR" => Some(Self::RestoreError),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod simulation_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct SimulationClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl SimulationClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> SimulationClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> SimulationClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            SimulationClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn build(
            &mut self,
            request: impl tonic::IntoRequest<super::BuildRequest>,
        ) -> std::result::Result<tonic::Response<super::BuildReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/Build",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("simulation.v1.Simulation", "Build"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn init(
            &mut self,
            request: impl tonic::IntoRequest<super::InitRequest>,
        ) -> std::result::Result<tonic::Response<super::InitReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/Init",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("simulation.v1.Simulation", "Init"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn init_and_run(
            &mut self,
            request: impl tonic::IntoRequest<super::InitAndRunRequest>,
        ) -> std::result::Result<
            tonic::Response<super::InitAndRunReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/InitAndRun",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("simulation.v1.Simulation", "InitAndRun"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn halt(
            &mut self,
            request: impl tonic::IntoRequest<super::HaltRequest>,
        ) -> std::result::Result<tonic::Response<super::HaltReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/Halt",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("simulation.v1.Simulation", "Halt"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn terminate(
            &mut self,
            request: impl tonic::IntoRequest<super::TerminateRequest>,
        ) -> std::result::Result<tonic::Response<super::TerminateReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/Terminate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("simulation.v1.Simulation", "Terminate"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn save(
            &mut self,
            request: impl tonic::IntoRequest<super::SaveRequest>,
        ) -> std::result::Result<tonic::Response<super::SaveReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/Save",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("simulation.v1.Simulation", "Save"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn restore(
            &mut self,
            request: impl tonic::IntoRequest<super::RestoreRequest>,
        ) -> std::result::Result<tonic::Response<super::RestoreReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/Restore",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("simulation.v1.Simulation", "Restore"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn restore_and_run(
            &mut self,
            request: impl tonic::IntoRequest<super::RestoreAndRunRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RestoreAndRunReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/RestoreAndRun",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("simulation.v1.Simulation", "RestoreAndRun"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn time(
            &mut self,
            request: impl tonic::IntoRequest<super::TimeRequest>,
        ) -> std::result::Result<tonic::Response<super::TimeReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/Time",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("simulation.v1.Simulation", "Time"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn step(
            &mut self,
            request: impl tonic::IntoRequest<super::StepRequest>,
        ) -> std::result::Result<tonic::Response<super::StepReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/Step",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("simulation.v1.Simulation", "Step"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn step_until(
            &mut self,
            request: impl tonic::IntoRequest<super::StepUntilRequest>,
        ) -> std::result::Result<tonic::Response<super::StepUntilReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/StepUntil",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("simulation.v1.Simulation", "StepUntil"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn run(
            &mut self,
            request: impl tonic::IntoRequest<super::RunRequest>,
        ) -> std::result::Result<tonic::Response<super::RunReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/Run",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("simulation.v1.Simulation", "Run"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_event_sources(
            &mut self,
            request: impl tonic::IntoRequest<super::ListEventSourcesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListEventSourcesReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/ListEventSources",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("simulation.v1.Simulation", "ListEventSources"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_event_source_schemas(
            &mut self,
            request: impl tonic::IntoRequest<super::GetEventSourceSchemasRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetEventSourceSchemasReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/GetEventSourceSchemas",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("simulation.v1.Simulation", "GetEventSourceSchemas"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_query_sources(
            &mut self,
            request: impl tonic::IntoRequest<super::ListQuerySourcesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListQuerySourcesReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/ListQuerySources",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("simulation.v1.Simulation", "ListQuerySources"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_query_source_schemas(
            &mut self,
            request: impl tonic::IntoRequest<super::GetQuerySourceSchemasRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetQuerySourceSchemasReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/GetQuerySourceSchemas",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("simulation.v1.Simulation", "GetQuerySourceSchemas"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_event_sinks(
            &mut self,
            request: impl tonic::IntoRequest<super::ListEventSinksRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListEventSinksReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/ListEventSinks",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("simulation.v1.Simulation", "ListEventSinks"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_event_sink_schemas(
            &mut self,
            request: impl tonic::IntoRequest<super::GetEventSinkSchemasRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetEventSinkSchemasReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/GetEventSinkSchemas",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("simulation.v1.Simulation", "GetEventSinkSchemas"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn inject_event(
            &mut self,
            request: impl tonic::IntoRequest<super::InjectEventRequest>,
        ) -> std::result::Result<
            tonic::Response<super::InjectEventReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/InjectEvent",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("simulation.v1.Simulation", "InjectEvent"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn schedule_event(
            &mut self,
            request: impl tonic::IntoRequest<super::ScheduleEventRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ScheduleEventReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/ScheduleEvent",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("simulation.v1.Simulation", "ScheduleEvent"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn cancel_event(
            &mut self,
            request: impl tonic::IntoRequest<super::CancelEventRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CancelEventReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/CancelEvent",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("simulation.v1.Simulation", "CancelEvent"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn process_event(
            &mut self,
            request: impl tonic::IntoRequest<super::ProcessEventRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ProcessEventReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/ProcessEvent",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("simulation.v1.Simulation", "ProcessEvent"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn schedule_query(
            &mut self,
            request: impl tonic::IntoRequest<super::ScheduleQueryRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ScheduleQueryReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/ScheduleQuery",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("simulation.v1.Simulation", "ScheduleQuery"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn process_query(
            &mut self,
            request: impl tonic::IntoRequest<super::ProcessQueryRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ProcessQueryReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/ProcessQuery",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("simulation.v1.Simulation", "ProcessQuery"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn try_read_events(
            &mut self,
            request: impl tonic::IntoRequest<super::TryReadEventsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TryReadEventsReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/TryReadEvents",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("simulation.v1.Simulation", "TryReadEvents"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn read_event(
            &mut self,
            request: impl tonic::IntoRequest<super::ReadEventRequest>,
        ) -> std::result::Result<tonic::Response<super::ReadEventReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/ReadEvent",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("simulation.v1.Simulation", "ReadEvent"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn enable_sink(
            &mut self,
            request: impl tonic::IntoRequest<super::EnableSinkRequest>,
        ) -> std::result::Result<
            tonic::Response<super::EnableSinkReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/EnableSink",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("simulation.v1.Simulation", "EnableSink"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn disable_sink(
            &mut self,
            request: impl tonic::IntoRequest<super::DisableSinkRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DisableSinkReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/simulation.v1.Simulation/DisableSink",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("simulation.v1.Simulation", "DisableSink"));
            self.inner.unary(req, path, codec).await
        }
    }
}
