---
title: "Hardware in the Loop Simulations"
filters:
  - line-highlight
toc-depth: 4
---

A common use case for NeXosim involves connecting simulation models to physical
hardware. In this tutorial we will go over the process of creating an interface
model and construct a bench that will communicate via a simulated serial
connection.

The simulation in this tutorial will consist of two models.
First is a simple `Counter` model, that counts the number of received bytes and
broadcasts the value through its output.
The other model, which will be the focus of this demonstration, is the
`SerialPort` model responsible for injecting the bytes received from an external
device through a serial connection into the simulation, as well as sending bytes
received from the simulation back to the device.

Since we can't really demonstrate a connection with a physical device, the
serial connection will be simulated using a pseudo TTY pair. The program will
construct the simulation and move it to its own thread. Then, two new threads
will be spawned with loops sending and receiving data respectively.

### Prerequisites

This tutorial uses the `mio` crate, and some familiarity with its API will
make understanding the included code easier.

### Dependencies

In this tutorial in addition to NeXosim, we'll be using a number of other
crates. Firstly [serde] – a framework for serializing and deserializing Rust
data structures. We'll always need `serde` when authoring models in NeXosim,
since all models are required to be serializable and deserializable.
The `SerialPort` model, for the purposes of serial communication,
will use [mio] – a popular low-level I/O library for Rust, and [mio-serial] – a
serial port implementation using mio.

The demonstration also uses [serialport-rs]. The crate similarly to mio-serial
provides a serial I/O interface, but does not have the async functionality.
Here we only use it to simulate an external device communicating with our
simulation by sending bytes over a pseudo TTY connection.

Both serial-rs and mio-serial require the `pkg-config` and `libudev` headers.
These can be installed by calling:

```bash
sudo apt update && sudo apt install pkg-config libudev-dev
```

The last crate we'll use [thread-guard] – a simple utility crate ensuring a
spawned thread is always joined, with optional pre- and post-joining actions.

It's worth mentioning that in this demonstration we don't perform any
decoding of the received data. In real applications we'd suggest
using a crate such as [bytes] to provide an abstraction for easier and more
efficient byte operations.

The PTY connection is established using the `socat` package. It can be installed
with the package manager:

```bash
sudo apt install socat
```

### Setup

To start with, let's create our project:

```bash
cargo new serial_port_model
cd serial_port_model
```

and add the required dependencies:

```bash
cargo add nexosim serde mio mio-serial serialport thread-guard
```

The dependencies table in `Cargo.toml` should look like this:

```toml
[dependencies]
mio = "1.1.1"
mio-serial = "5.0.6"
nexosim = "1.0.0"
serde = "1.0.228"
serialport = "4.8.1"
thread-guard = "0.1.0"
```

### Setting up Serial Communication

We'll implement the `SerialPort` model with the necessary functionality in the
`lib.rs`. Let's start by implementing a type responsible for establishing a
connection with a serial port.

```{.rust filename="src/lib.rs"}
use mio_serial::SerialPortBuilderExt;

const BAUD_RATE: u32 = 0;
const BUFFER_SIZE: usize = 256;

struct SerialPortInner {
    port: mio_serial::SerialStream,
    buffer: Vec<u8>,
}

impl SerialPortInner {
    fn new(port_path: &str) -> Self {
        Self {
            port: mio_serial::new(port_path, BAUD_RATE)
                .open_native_async()
                .unwrap(),
            buffer: vec![0; BUFFER_SIZE],
        }
    }
}
```

The `SerialPortInner` struct has a `Vec<u8>` buffer and a handle for the serial
I/O stream. When the struct is constructed with `SerialPortInner::new`,
a connection with the port at the specified path is opened, in a
platform-specific way. Since we won't be using a physical connection we can set
the baud rate to zero.

We'll add methods for I/O operations on the stream and a method for registering
the stream as an event source.

```rust
use std::io::{ErrorKind, Read, Result as IoResult, Write};

use mio::{Interest, Registry, Token};

const BAUD_RATE: u32 = 0;
const BUFFER_SIZE: usize = 256;

const STREAM_TOKEN: Token = Token(0);

// ...

impl SerialPortInner {

  // ...

  /// Registers the port in mio.
  fn register(&mut self, registry: &Registry) {
    registry.register(&mut self.port, STREAM_TOKEN, Interest::READABLE)
        .unwrap();
  }

  /// Reads data for the corresponding token.
  fn read(&mut self, token: Token) -> IoResult<Vec<u8>> {
      if token == STREAM_TOKEN {
          self.port
              .read(&mut self.buffer)
              .map(|len| Vec::from(&self.buffer[..len]))
      } else {
          Err(std::io::Error::new(
              ErrorKind::InvalidInput,
              "Unknown event.",
          ))
      }
  }

  /// Writes data.
  fn write(&mut self, data: &[u8]) -> IoResult<()> {
      self.port.write(data).map(|len| {
          if len != data.len() {
              Err(std::io::Error::other(format!(
                  "Not all bytes written: had to write {}, but wrote {}.",
                  data.len(),
                  len
              )))
          } else {
              Ok(())
          }
      })?
  }
}
```

The `register` method registers `SerialStream` as an event source in `mio::Poll`
instances registry and associates it with `STREAM_TOKEN`. When the Poll instance
is polled, events with this token will indicate that data was received and needs
to be read from the serial stream.

The `read` method ensures that the provided token matches the serial stream's
token. If it does, the method reads data from the port into the buffer and
return's the read bytes as a `Vec<u8>` wrapped in a `std::io::Result`.

`write` simply writes bytes to the stream, but returns an error
if it failed to write all the provided data.

#### The Event Loop

To prevent blocking of the simulation with I/O operations, we'll use
`SerialPortInner` in a separate thread with the mio event loop.
We'll create the `IoThread` type to serve as an abstraction around that thread
to make communication with the model easier.

```rust
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::mpsc::{Sender, channel};
use std::thread;

use mio::{Events, Poll, Waker};
use thread_guard::ThreadGuard;

use nexosim::model::SchedulableId;
use nexosim::simulation::ModelInjector;

const WAKER_TOKEN: Token = Token(1);

// ...

/// I/O Thread
struct IoThread {
    /// I/O thread guard.
    _io_thread: ThreadGuard<()>,
    /// Data transmitter.
    transmitter: Sender<Vec<u8>>,
    /// Thread waker.
    waker: Arc<Waker>,
}

impl IoThread {
    fn new(
        mut port: SerialPortInner,
        injector: ModelInjector<SerialPort>,
        schedulable: SchedulableId<SerialPort, Vec<u8>>,
    ) -> Self {
        let (transmitter, rx) = channel::<Vec<u8>>();

        let is_halted = Arc::new(AtomicBool::new(false));
        let guard_is_halted = is_halted.clone();

        let mut poll = Poll::new().unwrap();

        port.register(poll.registry());
        let waker = Arc::new(Waker::new(poll.registry(), WAKER_TOKEN).unwrap());
        let guard_waker = waker.clone();

        let io_thread = thread::spawn(move || {
            let mut events = Events::with_capacity(256);
            'poll: loop {
                poll.poll(&mut events, None).unwrap();

                for event in events.iter() {
                    let token = event.token();

                    match token {
                        STREAM_TOKEN => loop {
                            match port.read(token) {
                                Ok(message) => {
                                    injector.inject_event(&schedulable, message);
                                }
                                Err(ref e) if e.kind() == ErrorKind::WouldBlock => {
                                    break;
                                }
                                Err(_) => {
                                    break 'poll;
                                }
                            }
                        },
                        WAKER_TOKEN => {
                            if is_halted.load(Ordering::Relaxed) {
                                break 'poll;
                            }
                            while let Ok(data) = rx.try_recv() {
                                if port.write(&data).is_err() {
                                    break 'poll;
                                }
                            }
                        }
                        _ => (),
                    }
                }
            }
        });

        Self {
            _io_thread: ThreadGuard::with_pre_action(io_thread, move |_| {
                guard_is_halted.store(true, Ordering::Relaxed);
                let _ = guard_waker.wake();
                guard_waker
            }),
            transmitter,
            waker,
        }
    }
}
```

There's a lot happening here, so let's go over the `IoThread::new` function step-by-step.

The function, aside from the `SerialPortInner` instance, accepts a
`ModelInjector` and a `SchedulableId`.
The `ModelInjector` allows us to inject events to the associated model. This
means the event will be processed at the earliest opportunity, depending on the
bench setup. We'll go into more detail about event injection when constructing
the final bench.
The `SchedulableId` is used to identify the input port we want the event to be injected into.

:::{.callout-note}
The `ModelInjector` is being deprecated in NeXosim 1.1.0. It will be replaced
with the `EventInjector`, which doesn't use `SchedulableId` but instead injects
events to the input it was associated with when retrieving the injector.
:::

First, we instantiate a channel we'll use to send data to the thread.

```rust
let (transmitter, rx) = channel::<Vec<u8>>();
```

We define an atomic boolean representing whether the event loop is being
stopped. The `guard_is_halted` clone will later be moved to the thread guard's
pre-action closure, inside of which it is simply set to true, causing the thread
to exit the event loop. A thread guard's pre-action closure is called before the
thread is joined.

```rust
let is_halted = Arc::new(AtomicBool::new(false));
let guard_is_halted = is_halted.clone();
```

Next, we construct the `Poll` instance and register with it the
`SerialPortInner`. We also create a waker and register it with the
`WAKER_TOKEN`.

Whenever `Waker::wake` is called, a readiness event with the
associated token is created and will be read with the next `Poll::poll` call.
We'll use the waker whenever something in our program would demand an action in
the event loop. Specifically, when either we have data that we want to write to
the stream, or when we want to exit the event loop.

```rust
let mut poll = Poll::new().unwrap();

port.register(poll.registry());
let waker = Arc::new(Waker::new(poll.registry(), WAKER_TOKEN).unwrap());
let guard_waker = waker.clone();
```

We clone the waker and keep it as `guard_waker`. The clone will later be moved
to the thread guard's pre-action to signal the event loop should be exited.

We spawn the thread, instantiate an event collection and start the event loop.
In each iteration of the loop, first we poll for readiness events, and load the
events into the event collection. We iterate over each event and check their
tokens.

```rust
let io_thread = thread::spawn(move || {
    let mut events = Events::with_capacity(256);
    'poll: loop {
        poll.poll(&mut events, None).unwrap();
        for event in events.iter() {
            let token = event.token();

            match token {
```

When an event has the `STREAM_TOKEN` the `SerialPortInner` reads the data
from the serial stream and we inject an event containing the received data to
the `SerialPort` model using the provided `ModelInjector` and `SchedulableId`.
The stream is read in a loop until an error with `ErrorKind::WouldBlock` is
returned, indicating there is no more data to read. Other errors cause the
loop to exit.

```rust
STREAM_TOKEN => loop {
    match port.read(token) {
        Ok(message) => {
            injector.inject_event(&schedulable, message);
        }
        Err(ref e) if e.kind() == ErrorKind::WouldBlock => {
            break;
        }
        Err(_) => {
            break 'poll;
        }
    }
},
```

When an event's token is the `WAKER_TOKEN`, first we check the value
of the `is_halted` boolean. If true, the event loop is exited and the thread
completes. Otherwise, we continue and read the receiver of the channel
`rx` and write the received data to the serial stream.

We only expect events with either the `STREAM_TOKEN` and the `WAKER_TOKEN`,
so any other events are ignored.

```rust
WAKER_TOKEN => {
    if is_halted.load(Ordering::Relaxed) {
        break 'poll;
    }
    while let Ok(data) = rx.try_recv() {
        if port.write(&data).is_err() {
            break 'poll;
        }
    }
}
_ => (),
```

Finally, we construct our `IoThread` instance. We wrap the spawned thread in
a thread guard with a pre-action. The closure simply changes the `is_halted`
boolean to true and wakes up the Poll causing the event loop to exit.
The waker clone is returned from the closure to prevent unexpected behaviour due
to the waker being dropped before the waking could be registered.

The transmitter and waker are used as they were defined.

```rust
Self {
    _io_thread: ThreadGuard::with_pre_action(io_thread, move |_| {
        guard_is_halted.store(true, Ordering::Relaxed);
        let _ = guard_waker.wake();
        guard_waker
    }),
    transmitter,
    waker,
}
```

`IoThread` will have a method for sending messages to the thread. When sending
data to the thread we wake the `Poll` to signal to the `SerialPortInner`
instance that it needs to pass the data along to the serial stream.

```rust
/// Sends data to I/O thread.
fn send(&mut self, data: Vec<u8>) -> Result<(), String> {
    self.transmitter.send(data).map_err(|err| err.to_string())?;
    self.waker.wake().map_err(|err| err.to_string())?;
    Ok(())
}
```

### The Serial Port Model

We can finally construct the actual `SerialPort` model.
It will have a public input port `bytes_in` for forwarding data to the serial
stream, and a private input port `bytes_out` for forwarding data from the stream
to the output port.

We'll start with the more straightforward `bytes_out` input, which will simply
broadcast received data via the `bytes_out` output:

```rust
use nexosim::model::Model;
use serde::{Deserialize, Serialize};
use nexosim::ports::Output;

#[derive(Serialize, Deserialize)]
pub struct SerialPort {
    bytes_out: Output<Vec<u8>>,
}

#[Model]
impl SerialPort {
    /// Private port forwarding the raw bytes received on the serial port.
    #[nexosim(schedulable)]
    async fn bytes_out(&mut self, data: Vec<u8>) {
        self.bytes_out.send(data).await;
    }
}
```

We've marked the `bytes_out` input with `#[nexosim(schedulable)]`. This way we
will be later able to retrieve the port's `SchedulableId` for event injection.

Next is the `bytes_in` port, for which we'll need an `IoThread` instance, to be
able to send data to the serial port. However, before we start implementing the
method, there is an issue we have to address. NeXosim models must be
serializable, but we won't be able to serialize `IoThread`.

For such cases, where a model needs to use a non-serializable component, NeXosim
provides a workaround in the form of model environments:

```rust
#[Model(type Env = SerialPortEnv)]
impl SerialPort {
    // ...
}

pub struct SerialPortEnv {
    iothread: IoThread,
}
```

We've defined the `SerialPortEnv` struct with a single field holding the
`IoThread`. To set the type as the model's environment, we've modified the
`#[Model]` attribute to `#[Model(type Env = SerialPortEnv)]`.

To properly set up our environment we'll also need to implement a model
prototype for the `SerialPort`:

```rust
use nexosim::model::ProtoModel;
use nexosim::model::schedulable;

// ...


pub struct ProtoSerialPort {
    pub bytes_out: Output<Vec<u8>>,
    port_path: String,
}

impl ProtoSerialPort {
    pub fn new(port_path: &str) -> Self {
        Self {
            bytes_out: Output::default(),
            port_path: port_path.into(),
        }
    }
}

impl ProtoModel for ProtoSerialPort {
    type Model = SerialPort;

    fn build(
        self,
        cx: &mut nexosim::model::BuildContext<Self>,
    ) -> (Self::Model, <Self::Model as Model>::Env) {
        (
            SerialPort {
                bytes_out: self.bytes_out,
            },
            SerialPortEnv {
                iothread: IoThread::new(
                    SerialPortInner::new(&self.port_path),
                    cx.injector(),
                    *schedulable!(SerialPort::bytes_out),
                ),
            },
        )
    }
}

```

We've defined the `ProtoSerialPort` type with the port path and an output that
mirrors that of `SerialPort`. When using model prototypes, the prototype must have the same output and requestor ports, for us to be able to set up
connections.

```rust
pub struct ProtoSerialPort {
    pub bytes_out: Output<Vec<u8>>,
    port_path: String,
}

impl ProtoSerialPort {
    pub fn new(port_path: &str) -> Self {
        Self {
            bytes_out: Output::default(),
            port_path: port_path.into(),
        }
    }
}
```

For a type to serve as a model prototype, it must implement the `ProtoModel`
trait. We've pointed the `Model` alias at our `SerialModel` and implemented the
`ProtoModel::build` method.

The method implementation has to return the model and its environment. When
constructing the model we move the `bytes_out` output. To construct the
`SerialPortEnv` we first create the `SerialPortInner` instance using the stored
`port_path`. We retrieve the injector using the `BuildContext::injector` method,
and the `SchedulableId` with the `schedulable!` macro.

```rust
impl ProtoModel for ProtoSerialPort {
    type Model = SerialPort;

    fn build(
        self,
        cx: &mut nexosim::model::BuildContext<Self>,
    ) -> (Self::Model, <Self::Model as Model>::Env) {
        (
            SerialPort {
                bytes_out: self.bytes_out,
            },
            SerialPortEnv {
                iothread: IoThread::new(
                    SerialPortInner::new(&self.port_path),
                    cx.injector(),
                    *schedulable!(SerialPort::bytes_out),
                ),
            },
        )
    }
}
```

Finally we can implement the `bytes_in` input port. The method simply accesses
the iothread through the environment and uses the send method we've implemented
earlier. To access the model's `Env` we just have to use the appropriate
signature when defining the port.

```rust
use nexosim::model::Context;

// ...

#[Model(type Env = SerialPortEnv)]
impl SerialPort {
    /// Sends raw bytes to the serial port -- input port.
    pub fn bytes_in(&mut self, data: Vec<u8>, _: &Context<Self>, env: &mut SerialPortEnv) {
        env.iothread.send(data).unwrap();
    }

    // ...
}
```


::: {.callout-note collapse="true"}
## The complete `lib.rs` should look like this:

```rust
use mio::{Events, Interest, Poll, Registry, Token, Waker};
use mio_serial::SerialPortBuilderExt;
use nexosim::model::{Context, Model, ProtoModel, SchedulableId, schedulable};
use nexosim::ports::Output;
use nexosim::simulation::ModelInjector;
use serde::{Deserialize, Serialize};
use std::io::{ErrorKind, Read, Result as IoResult, Write};
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::mpsc::{Sender, channel};
use std::thread;
use thread_guard::ThreadGuard;

const BAUD_RATE: u32 = 0;
const BUFFER_SIZE: usize = 256;

const STREAM_TOKEN: Token = Token(0);
const WAKER_TOKEN: Token = Token(1);

struct SerialPortInner {
    port: mio_serial::SerialStream,
    buffer: Vec<u8>,
}

impl SerialPortInner {
    fn new(port_path: &str) -> Self {
        Self {
            port: mio_serial::new(port_path, BAUD_RATE)
                .open_native_async()
                .unwrap(),
            buffer: vec![0; BUFFER_SIZE],
        }
    }

    /// Registers the port in mio.
    fn register(&mut self, registry: &Registry) {
        registry
            .register(&mut self.port, STREAM_TOKEN, Interest::READABLE)
            .unwrap();
    }

    /// Reads data for the corresponding token.
    fn read(&mut self, token: Token) -> IoResult<Vec<u8>> {
        if token == STREAM_TOKEN {
            self.port
                .read(&mut self.buffer)
                .map(|len| Vec::from(&self.buffer[..len]))
        } else {
            Err(std::io::Error::new(
                ErrorKind::InvalidInput,
                "Unknown event.",
            ))
        }
    }

    /// Writes data.
    fn write(&mut self, data: &[u8]) -> IoResult<()> {
        self.port.write(data).map(|len| {
            if len != data.len() {
                Err(std::io::Error::other(format!(
                    "Not all bytes written: had to write {}, but wrote {}.",
                    data.len(),
                    len
                )))
            } else {
                Ok(())
            }
        })?
    }
}

/// I/O Thread
struct IoThread {
    /// I/O thread guard.
    _io_thread: ThreadGuard<()>,
    /// Data transmitter.
    transmitter: Sender<Vec<u8>>,
    /// Thread waker.
    waker: Arc<Waker>,
}

impl IoThread {
    fn new(
        mut port: SerialPortInner,
        injector: ModelInjector<SerialPort>,
        schedulable: SchedulableId<SerialPort, Vec<u8>>,
    ) -> Self {
        let (transmitter, rx) = channel::<Vec<u8>>();

        let is_halted = Arc::new(AtomicBool::new(false));
        let guard_is_halted = is_halted.clone();

        let mut poll = Poll::new().unwrap();

        port.register(poll.registry());
        let waker = Arc::new(Waker::new(poll.registry(), WAKER_TOKEN).unwrap());
        let guard_waker = waker.clone();

        let io_thread = thread::spawn(move || {
            let mut events = Events::with_capacity(256);
            'poll: loop {
                poll.poll(&mut events, None).unwrap();

                for event in events.iter() {
                    let token = event.token();

                    match token {
                        STREAM_TOKEN => loop {
                            match port.read(token) {
                                Ok(message) => {
                                    injector.inject_event(&schedulable, message);
                                }
                                Err(ref e) if e.kind() == ErrorKind::WouldBlock => {
                                    break;
                                }
                                Err(_) => {
                                    break 'poll;
                                }
                            }
                        },
                        WAKER_TOKEN => {
                            if is_halted.load(Ordering::Relaxed) {
                                break 'poll;
                            }
                            while let Ok(data) = rx.try_recv() {
                                if port.write(&data).is_err() {
                                    break 'poll;
                                }
                            }
                        }
                        _ => (),
                    }
                }
            }
        });

        Self {
            _io_thread: ThreadGuard::with_pre_action(io_thread, move |_| {
                guard_is_halted.store(true, Ordering::Relaxed);
                let _ = guard_waker.wake();
                guard_waker
            }),
            transmitter,
            waker,
        }
    }

    /// Sends data to I/O thread.
    fn send(&mut self, data: Vec<u8>) -> Result<(), String> {
        self.transmitter.send(data).map_err(|err| err.to_string())?;
        self.waker.wake().map_err(|err| err.to_string())?;
        Ok(())
    }
}

#[derive(Serialize, Deserialize)]
pub struct SerialPort {
    bytes_out: Output<Vec<u8>>,
}

#[Model(type Env = SerialPortEnv)]
impl SerialPort {
    /// Sends raw bytes to the serial port -- input port.
    pub fn bytes_in(&mut self, data: Vec<u8>, _: &Context<Self>, env: &mut SerialPortEnv) {
        env.iothread.send(data).unwrap();
    }

    /// Private port forwarding the raw bytes received on the serial port.
    #[nexosim(schedulable)]
    async fn bytes_out(&mut self, data: Vec<u8>) {
        self.bytes_out.send(data).await;
    }
}

pub struct SerialPortEnv {
    iothread: IoThread,
}

pub struct ProtoSerialPort {
    pub bytes_out: Output<Vec<u8>>,
    port_path: String,
}

impl ProtoSerialPort {
    pub fn new(port_path: &str) -> Self {
        Self {
            bytes_out: Output::default(),
            port_path: port_path.into(),
        }
    }
}

impl ProtoModel for ProtoSerialPort {
    type Model = SerialPort;

    fn build(
        self,
        cx: &mut nexosim::model::BuildContext<Self>,
    ) -> (Self::Model, <Self::Model as Model>::Env) {
        (
            SerialPort {
                bytes_out: self.bytes_out,
            },
            SerialPortEnv {
                iothread: IoThread::new(
                    SerialPortInner::new(&self.port_path),
                    cx.injector(),
                    *schedulable!(SerialPort::bytes_out),
                ),
            },
        )
    }
}
```

:::

### Simulation Setup

We have completed the `SerialPort` model, and we can now test it out in a
simulation.

We'll start by creating the `Counter` model in `main.rs`:

```{.rust filename="src/main.rs"}
use nexosim::model::Model;
use nexosim::ports::Output;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Default)]
struct Counter {
    pub count: Output<u32>,
    _count: u32,
}

#[Model]
impl Counter {
    async fn bytes_in(&mut self, bytes: Vec<u8>) {
        self._count += bytes.len() as u32;
        self.count.send(self._count).await;
    }
}
```

When the model receives a sequence of bytes to its `bytes_in` input port, it
increases the stored count by the number of bytes in the sequence and
broadcasts the resulting value through `count` output.

In the `main` function we'll instantiate and connect up the two models, and add
them to the simulation.

```rust
use std::time::Duration;

use nexosim::ports::{SinkState, event_queue};
use nexosim::simulation::{Mailbox, SimInit, SimulationError};
use nexosim::time::{AutoSystemClock, MonotonicTime, PeriodicTicker};

use serial_port_model::{ProtoSerialPort, SerialPort};

// ...

const INTERNAL_PORT_PATH: &str = "/tmp/ttyS20";
const TICKER_PERIOD: Duration = Duration::from_millis(100);

// ...

fn main() -> Result<(), SimulationError> {
    let mut port = ProtoSerialPort::new(INTERNAL_PORT_PATH);
    let port_mbox = Mailbox::new();

    let mut counter = Counter::default();
    let counter_mbox = Mailbox::new();

    let (sink, mut count_reader) = event_queue(SinkState::Enabled);
    counter.count.connect_sink(sink);

    port.bytes_out.connect(Counter::bytes_in, &counter_mbox);

    counter.count.map_connect(
        |count| Vec::from(count.to_ne_bytes()),
        SerialPort::bytes_in,
        &port_mbox,
    );

    let mut sim = SimInit::new()
        .add_model(port, port_mbox, "SERIAL_PORT")
        .add_model(counter, counter_mbox, "COUNTER")
        .with_clock(AutoSystemClock::new(), PeriodicTicker::new(TICKER_PERIOD))
        .init(MonotonicTime::EPOCH)?;

    Ok(())
}
```

We connect the prototype's outputs and add it to the simulation the same
way we would a regular model.

We use `tmp/ttyS20` as the port path for the `SerialPort` model.
This path will be later used when creating a pseudo TTY connection with socat.

To connect the `count` output to the `bytes_in` input we use a mapped connection
that the `u32` value to a native endian byte vector.

```rust
counter.count.map_connect(
    |c| Vec::from(c.to_ne_bytes()),
    SerialPort::bytes_in,
    &port_mbox,
);
```

We've also added an event queue and connected its writer to the `count` output
so we can monitor the broadcast events.

```rust
let (sink, mut count_reader) = event_queue(SinkState::Enabled);
counter.count.connect_sink(sink);
```

In hardware in the loop simulations we have to synchronize the simulation
with a real-time clock. In NeXosim we do this with a `SimInit::with_clock` call.
Here we use the `AutoSystemClock` which synchronizes the simulation with the
system's clock and is initialized when its first synchronized (usually this will
be when `SimInit::init` is called).

We also set a ticker. A `Ticker` forces the synchronization clock to wake up,
and make the simulation check for commands or injected events. Injected events
are processed at the earliest possible opportunity. This will be either at the
next tick or time of the next scheduled event, whichever occurs first. When the simulation isn't set up with a ticker, injected events are processed only with other scheduled events.

Here we use a `PeriodicTicker` with the period set to 100 ms, which means every
100 ms the `SerialPort` model will check if any bytes were received from the
`IoThread`, and forward them to the `bytes_out` output.

```{.rust source-line-numbers="4"}
let mut sim = SimInit::new()
    .add_model(port, port_mbox, "SERIAL_PORT")
    .add_model(counter, counter_mbox, "COUNTER")
    .with_clock(AutoSystemClock::new(), PeriodicTicker::new(TICKER_PERIOD))
    .init(MonotonicTime::EPOCH)?;
```

Instead of controlling the simulation directly, the program communicate with the
`SerialPort` model through a simulated serial connection. To be able to do that
in the same program we'll have to move the simulation and communication
operations to their own threads.

First we'll create the simulation thread:

```rust
use std::thread;
use thread_guard::ThreadGuard;

// ...

let scheduler = sim.scheduler();

let simulation_handle = ThreadGuard::with_actions(
    thread::spawn(move || sim.run()),
    move |_| scheduler.halt(),
    |_, result| println!("Simulation thread result: {:?}.", result),
);
```

The thread simply calls `Simulation::run` to make the
simulation progress until its halted. The halting occurs in the guard's
pre-action, with the `Scheduler::halt` call, right before the thread is joined.

We'll also create two additional threads responsible for the serial
communication – one for sending and one for receiving bytes.

```rust
use std::thread::sleep;

const EXTERNAL_PORT_PATH: &str = "/tmp/ttyS21";
const BAUD_RATE: u32 = 0;

/// Number of bytes to send.
const N: u8 = 10;

// ...

fn main() -> Result<(), SimulationError> {

    // ...

    let mut sender_port = serialport::new(EXTERNAL_PORT_PATH, BAUD_RATE)
        .open()
        .unwrap();

    let mut receiver_port = sender_port.try_clone().unwrap();

    let sender_thread = ThreadGuard::new(thread::spawn(move || {
        for i in 0..N {
            if i % 3 == 0 {
                sleep(Duration::from_secs(1));
            }
            sender_port.write_all(&[0xAA]).unwrap();
        }
    }));

    let receiver_thread = ThreadGuard::new(thread::spawn(move || {
        let mut buffer = [0; 10];
        let mut count = 0;

        for _ in 0..N {
            sleep(Duration::from_secs(1));
            if let Ok(n) = receiver_port.read(&mut buffer) {
                if n >= 4 {
                    count = <u32>::from_ne_bytes(buffer[0..4].try_into().unwrap());
                    if count >= N.into() {
                        break;
                    }
                }
            }
        }
        count as u8
    }));
}
```

The serial communication from the threads is handled by the `serialport` crate.
We create a port with the path `/tmp/ttyS21` and set its baud rate to 0 like we
did for the `SerialPort` model's port. The port is cloned so it can be used
in both of the threads.

The sender thread sends out ten bytes, waiting for a second every third
byte.

```rust
let sender_thread = ThreadGuard::new(thread::spawn(move || {
    for i in 0..N {
        if i % 3 == 0 {
            sleep(Duration::from_secs(1));
        }
        sender_port.write_all(&[0xAA]).unwrap();
    }
}));
```

The receiver thread every second reads into a buffer, the data received on
the port. If any bytes were received, they are converted into a `u32`
representing the number of bytes counted by the `Counter` model. This happens
until the count value reaches ten or up to ten seconds. The final count is
returned and will later be used to verify the simulation is working correctly.

It's worth noting that the way the incoming data is processed is naive. It
works on the assumption that between each iteration, at most only one value was
sent.

```rust
let receiver_thread = ThreadGuard::new(thread::spawn(move || {
    let mut buffer = [0; 10];
    let mut count = 0;

    for _ in 0..N {
        sleep(Duration::from_secs(1));
        if let Ok(n) = receiver_port.read(&mut buffer) {
            if n != 0 {
                count =
                    <u32>::from_ne_bytes(buffer[0..4].try_into().unwrap());
                if count >= N.into() {
                    break;
                }
            }
        }
    }
    count as u8
}));
```

All three threads are wrapped in a thread guard to ensure all the threads are
joined.

To monitor the simulation we'll set up a loop that awaits events on the
event queue reader we've set up earlier.

```rust
use nexosim::ports::EventSinkReader;

// ...

const TIMEOUT: Duration = Duration::new(5, 0);

// ...

fn main() -> Result<(), SimulationError> {
    // ...

    loop {
        let mut t = Duration::new(0, 0);
        let mut counted = count_reader.try_read();
        while t < TIMEOUT && counted.is_none() {
            sleep(TICKER_PERIOD);
            t += TICKER_PERIOD;
            counted = count_reader.try_read()
        }

        if let Some(count) = counted {
            println!("Counted {count} bytes");
            if count >= N.into() {
                break;
            }
        } else {
            panic!("Unexpected timeout or simulation halt!")
        }
    }
```

The loop periodically checks for any new events with the
`EventSinkReader::try_read` method. If no events were received within 5 seconds,
the program panics. The loop exits when an event with a value greater than or
equal to the expected ten bytes, and prints out the final number of counted
bytes.

Finally we join all the threads. As mentioned earlier, the final count
returned by the receiver thread is used to verify that all ten bytes were
counted and the count value was sent back.

```rust
use nexosim::simulation::ExecutionError;

// ...

fn main() -> Result<(), SimulationError> {
    // ...

    match simulation_handle.join().unwrap() {
        Err(ExecutionError::Halted) => {}
        Err(e) => return Err(e.into()),
        _ => {}
    }
    sender_thread.join().unwrap();

    assert_eq!(N, receiver_thread.join().unwrap());

    Ok(())
}
```

### Testing It Out

To test out our setup first we need to create the pseudo TTY pair. In a
separate terminal run:

```bash
socat -d3 pty,raw,echo=0,link=/tmp/ttyS21 pty,raw,echo=0,link=/tmp/ttyS20
```

Now we can run our program:

```bash
cargo run
```

and we'll see:

```
Counted 3 bytes
Counted 6 bytes
Counted 9 bytes
Counted 10 bytes
```

::: {.callout-note collapse="true"}
## The complete `main.rs` should look like this:

```rust
use std::thread;
use std::thread::sleep;
use std::time::Duration;

use serial_port_model::{ProtoSerialPort, SerialPort};
use nexosim::model::Model;
use nexosim::ports::{EventSinkReader, Output, SinkState, event_queue};
use nexosim::simulation::{ExecutionError, Mailbox, SimInit, SimulationError};
use nexosim::time::{AutoSystemClock, MonotonicTime, PeriodicTicker};
use serde::{Deserialize, Serialize};
use thread_guard::ThreadGuard;

const INTERNAL_PORT_PATH: &str = "/tmp/ttyS20";
const EXTERNAL_PORT_PATH: &str = "/tmp/ttyS21";

const BAUD_RATE: u32 = 0;

const TICKER_PERIOD: Duration = Duration::from_millis(100);
const TIMEOUT: Duration = Duration::new(5, 0);

/// Number of bytes to send.
const N: u8 = 10;

#[derive(Serialize, Deserialize, Default)]
struct Counter {
    pub count: Output<u32>,
    _count: u32,
}

#[Model]
impl Counter {
    async fn bytes_in(&mut self, bytes: Vec<u8>) {
        self._count += bytes.len() as u32;
        self.count.send(self._count).await;
    }
}

fn main() -> Result<(), SimulationError> {
    let mut port = ProtoSerialPort::new(INTERNAL_PORT_PATH);
    let port_mbox = Mailbox::new();

    let mut counter = Counter::default();
    let counter_mbox = Mailbox::new();

    let (sink, mut count_reader) = event_queue(SinkState::Enabled);
    counter.count.connect_sink(sink);

    port.bytes_out.connect(Counter::bytes_in, &counter_mbox);

    counter.count.map_connect(
        |c| Vec::from(c.to_ne_bytes()),
        SerialPort::bytes_in,
        &port_mbox,
    );

    let mut sim = SimInit::new()
        .add_model(port, port_mbox, "SERIAL_PORT")
        .add_model(counter, counter_mbox, "COUNTER")
        .with_clock(AutoSystemClock::new(), PeriodicTicker::new(TICKER_PERIOD))
        .init(MonotonicTime::EPOCH)?;

    let scheduler = sim.scheduler();

    let simulation_handle = ThreadGuard::with_actions(
        thread::spawn(move || sim.run()),
        move |_| scheduler.halt(),
        |_, result| println!("Simulation thread result: {:?}.", result),
    );

    let mut sender_port = serialport::new(EXTERNAL_PORT_PATH, BAUD_RATE)
        .open()
        .unwrap();

    let mut receiver_port = sender_port.try_clone().unwrap();

    let sender_thread = ThreadGuard::new(thread::spawn(move || {
        for i in 0..N {
            if i % 3 == 0 {
                sleep(Duration::from_secs(1));
            }
            sender_port.write_all(&[0xAA]).unwrap();
        }
    }));

    let receiver_thread = ThreadGuard::new(thread::spawn(move || {
        let mut buffer = [0; 10];
        let mut count = 0;

        for _ in 0..N {
            sleep(Duration::from_secs(1));
            if let Ok(n) = receiver_port.read(&mut buffer) {
                if n >= 4 {
                    count = <u32>::from_ne_bytes(buffer[0..4].try_into().unwrap());
                    if count >= N.into() {
                        break;
                    }
                }
            }
        }
        count as u8
    }));

    loop {
        let mut t = Duration::new(0, 0);
        let mut counted = count_reader.try_read();
        while t < TIMEOUT && counted.is_none() {
            sleep(TICKER_PERIOD);
            t += TICKER_PERIOD;
            counted = count_reader.try_read()
        }

        if let Some(count) = counted {
            println!("Counted {count} bytes");
            if count >= N.into() {
                break;
            }
        } else {
            panic!("Unexpected timeout or simulation halt!")
        }
    }

    match simulation_handle.join().unwrap() {
        Err(ExecutionError::Halted) => {}
        Err(e) => return Err(e.into()),
        _ => {}
    }
    sender_thread.join().unwrap();

    assert_eq!(N, receiver_thread.join().unwrap());

    Ok(())
}
```
:::
[serde]: https://github.com/serde-rs/serde
[mio]: https://github.com/tokio-rs/mio
[mio-serial]: https://github.com/berkowski/mio-serial
[serialport-rs]: https://github.com/serialport/serialport-rs
[thread-guard]: https://github.com/asynchronics/thread-guard
[bytes]: https://github.com/tokio-rs/bytes